# Generated by Django 4.2.2 on 2023-10-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REVAA_RDS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Employee_Number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
