# Generated by Django 4.2.2 on 2023-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REVAA_RDS_APP', '0002_alter_customuser_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='creator',
        ),
    ]
